pipeline:
  name: NodeJSCI
  identifier: NodeJSCI
  projectIdentifier: EEEProject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: PersonalGitHub
        repoName: <+input>
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: true
            paths: []
          buildIntelligence:
            enabled: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: org.githubcodespaceCluster
              namespace: dev
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: org.MyDockerReg
                    repo: <+input>
                    tags:
                      - tag
